spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=postgres
spring.datasource.password=brayanjavier21
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

detection.service.url=http://localhost:8001

jwt.secret=miSuperSecretoJWT1234567890123456789012345678
jwt.expiration=86400000

spring.main.allow-circular-references=true