spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventory}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:brayanjavier21}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Rome

detection.service.url=${DETECTION_SERVICE_URL:http://localhost:8001}

jwt.secret=${JWT_SECRET:miSuperSecretoJWT1234567890123456789012345678}
jwt.expiration=86400000

spring.main.allow-circular-references=true
server.port=${PORT:8080}